<?php

namespace FeedBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FeedsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeedsRepository extends EntityRepository
{
    public function getFeedCategories()
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('f.category')
            ->from($this->_entityName, 'f')
            ->distinct()
        ;

        return $qb->getQuery()->execute();
    }
}
